from django.urls import path

from .views import (
    StudentDashboardAPIView,
    StudentProfileAPIView,
    StudentLoginAPIView,
    TeacherDashboardView,
    TeacherProfileAPIView,
    TeacherLoginAPIView,
    CollegeAdminDashboardAPIView,
    CollegeAdminLoginAPIView,
    CollegeAdminStudentDetailAPIView,
    CollegeAdminStudentsAPIView,
    ParentLoginAPIView,
    ParentChildrenAPIView,
    ParentProfileAPIView,
)

urlpatterns = [
    path(
        'student/dashboard/',
        StudentDashboardAPIView.as_view(),
        name='student-dashboard'
    ),
    path(
    'student/profile/',
    StudentProfileAPIView.as_view(),
    name='student-profile'
),
    path(
    'student/login/',
    StudentLoginAPIView.as_view(),
    name='student-login'
),
    path(
    "teacher/dashboard/",
    TeacherDashboardView.as_view(),
    name="teacher-dashboard",
),
    path(
    "teacher/profile/",
    TeacherProfileAPIView.as_view(),
    name="teacher-profile",
),
    path(
    "teacher/login/",
    TeacherLoginAPIView.as_view(),
    name="teacher-login",
),
    path(
    "college-admin/login/",
    CollegeAdminLoginAPIView.as_view(),
    name="college-admin-login",
),
    path(
    "college-admin/dashboard/",
    CollegeAdminDashboardAPIView.as_view(),
    name="college-admin-dashboard",
),
    path(
    "college-admin/students/",
    CollegeAdminStudentsAPIView.as_view(),
    name="college-admin-students",
),
    path(
    "college-admin/students/<int:student_id>/",
    CollegeAdminStudentDetailAPIView.as_view(),
    name="college-admin-student-detail",
),
    path(
    "parent/login/",
    ParentLoginAPIView.as_view(),
    name="parent-login",
),  
    path(
    "parent/children/",
    ParentChildrenAPIView.as_view(),
    name="parent-children",
),
    path(
    "parent/profile/",
    ParentProfileAPIView.as_view(),
    name="parent-profile",
),
]
