# Generated by Django 6.0 on 2026-10-03 05:18

import django.core.files.storage
import django.core.validators
import pathlib
import recordedcourses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordedcourses', '0002_alter_recordedlesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordedlesson',
            name='video',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('E:/tech/private_media')), upload_to=recordedcourses.models.recorded_lesson_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov'])]),
        ),
    ]
