from django.urls import path

from .views import (
    TeacherResultsSetupAPIView,
    TeacherExamCreateAPIView,
    TeacherExamStudentsAPIView,
    TeacherSaveExamMarksAPIView,
    TeacherExamListAPIView,
    TeacherPublishExamAPIView,
    StudentResultsAPIView,
    ParentStudentResultsAPIView,
    CollegeAdminResultsAPIView,
    CollegeAdminResultsSetupAPIView,
    CollegeAdminResultDetailAPIView,
)


from .online_exams import (
    TeacherOnlineExamListCreateAPIView,
    TeacherOnlineExamDetailAPIView,
    TeacherOnlineExamOpenAPIView,
    TeacherOnlineExamAttemptsAPIView,
    TeacherOnlineExamGradeAPIView,
    StudentOnlineExamListAPIView,
    StudentOnlineExamDetailAPIView,
    StudentOnlineExamStartAPIView,
    StudentOnlineExamAnswerAPIView,
    StudentOnlineExamSubmitAPIView,
)

urlpatterns = [
    path(
        "teacher/online-exams/",
        TeacherOnlineExamListCreateAPIView.as_view(),
        name="teacher-online-exams",
    ),
    path(
        "teacher/online-exams/<int:exam_id>/",
        TeacherOnlineExamDetailAPIView.as_view(),
        name="teacher-online-exam-detail",
    ),
    path(
        "teacher/online-exams/<int:exam_id>/open/",
        TeacherOnlineExamOpenAPIView.as_view(),
        name="teacher-online-exam-open",
    ),
    path(
        "teacher/online-exams/<int:exam_id>/attempts/",
        TeacherOnlineExamAttemptsAPIView.as_view(),
        name="teacher-online-exam-attempts",
    ),
    path(
        "teacher/online-exams/<int:exam_id>/attempts/<int:attempt_id>/questions/<int:question_id>/grade/",
        TeacherOnlineExamGradeAPIView.as_view(),
        name="teacher-online-exam-grade",
    ),
    path(
        "student/online-exams/",
        StudentOnlineExamListAPIView.as_view(),
        name="student-online-exams",
    ),
    path(
        "student/online-exams/<int:exam_id>/",
        StudentOnlineExamDetailAPIView.as_view(),
        name="student-online-exam-detail",
    ),
    path(
        "student/online-exams/<int:exam_id>/start/",
        StudentOnlineExamStartAPIView.as_view(),
        name="student-online-exam-start",
    ),
    path(
        "student/online-exams/<int:exam_id>/questions/<int:question_id>/answer/",
        StudentOnlineExamAnswerAPIView.as_view(),
        name="student-online-exam-answer",
    ),
    path(
        "student/online-exams/<int:exam_id>/submit/",
        StudentOnlineExamSubmitAPIView.as_view(),
        name="student-online-exam-submit",
    ),

    path(
        "teacher/setup/",
        TeacherResultsSetupAPIView.as_view(),
        name="teacher-results-setup",
    ),
    path(
    "teacher/exams/create/",
    TeacherExamCreateAPIView.as_view(),
    name="teacher-exam-create",
),
    path(
    "teacher/exams/<int:exam_id>/students/",
    TeacherExamStudentsAPIView.as_view(),
    name="teacher-exam-students",
),

path(
    "teacher/exams/<int:exam_id>/marks/",
    TeacherSaveExamMarksAPIView.as_view(),
    name="teacher-save-exam-marks",
),
path(
    "teacher/exams/",
    TeacherExamListAPIView.as_view(),
    name="teacher-exam-list",
),
path(
    "teacher/exams/<int:exam_id>/publish/",
    TeacherPublishExamAPIView.as_view(),
    name="teacher-publish-exam",
),
path(
    "student/",
    StudentResultsAPIView.as_view(),
    name="student-results",
),
path(
    "parent/student/<int:student_id>/",
    ParentStudentResultsAPIView.as_view(),
    name="parent-student-results",
),
path(
    "college-admin/",
    CollegeAdminResultsAPIView.as_view(),
    name="college-admin-results",
),
path(
    "college-admin/setup/",
    CollegeAdminResultsSetupAPIView.as_view(),
    name="college-admin-results-setup",
),
path(
    "college-admin/<int:exam_id>/",
    CollegeAdminResultDetailAPIView.as_view(),
    name="college-admin-result-detail",
),
    
]
